### ISSUE TITLE
将「单向超链接」描述改为「块超链接」

### ISSUE THREAD

**Issue by TCOTC** [hqweay/siyuan-href-to-ref#3]
![image](https://github.com/hqweay/siyuan-href-to-ref/assets/78434827/715b559d-c4f3-4f10-a36c-c41607378168)

**Comment by hqweay** [comment]
> ![image](https://private-user-images.githubusercontent.com/78434827/320221049-715b559d-c4f3-4f10-a36c-c41607378168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTIwOTcsIm5iZiI6MTcxMjQ1MTc5NywicGF0aCI6Ii83ODQzNDgyNy8zMjAyMjEwNDktNzE1YjU1OWQtYzRmMy00ZjEwLWEzNmMtYzQxNjA3Mzc4MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAxMDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MThhMTVhZjQ1YWNiMTc5ODg0ZTM0NDM2OWI2ZTE5MzNmMmY2YjQ4M2YxMTJkYTZjOTYzOTU3ZTc4Mjk0ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLPW75eyGRsMWyLDGJD8kHKc9rboPMX30KhxC8FyryE)

单向超链接指软件内笔记的链接；
链接泛指所有。

TCOTC 你有更合适的名称吗？

**Comment by TCOTC** [comment]
> 链接泛指所有

我不清楚「链接」都有哪些类型？

**Comment by hqweay** [comment]
> > 链接泛指所有
> 
> 我不清楚「链接」都有哪些类型？

技术上指 a 标签，思源内是属性 data-type 为 a 的内容块。

使用上我拿 单向超链接 指 引用思源内部笔记的链接。
链接 则 不区分引用内容。包括单向超链接，引用网址，引用文件，引用其它外部链接…

**Comment by TCOTC** [comment]
这样的话，「单向超链接」改成「块超链接」吧，在概念上统一：

![image](https://github.com/hqweay/siyuan-href-to-ref/assets/78434827/ed1f68f6-740b-4ef4-a96a-d93d8051038c)

**Comment by hqweay** [comment]
> 这样的话，「单向超链接」改成「块超链接」吧，在概念上统一：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/320265200-ed1f68f6-740b-4ef4-a96a-d93d8051038c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTA4NjgsIm5iZiI6MTcxMjQ5MDU2OCwicGF0aCI6Ii83ODQzNDgyNy8zMjAyNjUyMDAtZWQxZjY4ZjYtNzQwYi00ZWY0LWE5NmEtZDkzZDgwNTEwMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExNDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTAyOGM1MWQyMzFjZTFmYjg2YzVmMDIzNGU3MGE3NTI3ZGVjOGI2ZjAyYWYxZTM4YzkxYWVmOTM1Y2NmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SPMZqCuSpIUvWwykNHKB9976IIdQl-PjFLnqoij9mI)

感谢，调整了下。
