### ISSUE TITLE
能否增加"斜体 👉 文本"？

### ISSUE THREAD

**Issue by yshumy** [hqweay/siyuan-href-to-ref#6]
还有"上下标 👉 文本"等等。

**Comment by hqweay** [comment]
可以，我瞧瞧。现在选项有点多，可能得加个开关了…

**Comment by hqweay** [comment]
斜体加上了。
不过这个项目维护到 https://github.com/hqweay/siyuan-hqweay-go 这里了，过阵子集市应该就会有。
